// <auto-generated />
using System;
using BeatSlayerServer.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeatSlayerServer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200531225712_upgradePreprint")]
    partial class upgradePreprint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<long>("AllScore")
                        .HasColumnType("bigint");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("Hits")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("InGameTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("LastActiveTimeUtc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("datetime");

                    b.Property<int>("MapsPublished")
                        .HasColumnType("int");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("int");

                    b.Property<int>("Misses")
                        .HasColumnType("int");

                    b.Property<string>("Nick")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("PlaceInRanking")
                        .HasColumnType("int");

                    b.Property<int>("PublishedMapsLiked")
                        .HasColumnType("int");

                    b.Property<int>("PublishedMapsPlayed")
                        .HasColumnType("int");

                    b.Property<double>("RP")
                        .HasColumnType("double");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("SignUpTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Accounts.GroupInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Accounts.MapInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Nick")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("MapInfo");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Accounts.ReplayInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CubesSliced")
                        .HasColumnType("int");

                    b.Property<string>("DifficultyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyStars")
                        .HasColumnType("int");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<int>("Missed")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("RP")
                        .HasColumnType("double");

                    b.Property<float>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Email.CodeVerificationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Nick")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VerificationRequests");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Notifications.NotificationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("RequesterNick")
                        .HasColumnType("text");

                    b.Property<string>("TargetNick")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Accounts.Account", b =>
                {
                    b.HasOne("BeatSlayerServer.Multiplayer.Accounts.Account", null)
                        .WithMany("Friends")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Accounts.MapInfo", b =>
                {
                    b.HasOne("BeatSlayerServer.Multiplayer.Accounts.GroupInfo", "Group")
                        .WithMany("Maps")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Accounts.ReplayInfo", b =>
                {
                    b.HasOne("BeatSlayerServer.Multiplayer.Accounts.MapInfo", "Map")
                        .WithMany("Replays")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeatSlayerServer.Multiplayer.Accounts.Account", "Player")
                        .WithMany("Replays")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeatSlayerServer.Multiplayer.Notifications.NotificationInfo", b =>
                {
                    b.HasOne("BeatSlayerServer.Multiplayer.Accounts.Account", null)
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
