name: Production pushing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH commmands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd "/source/ServerProduction/BeatSlayerServer"
            git pull origin master
            sudo dotnet publish -c release -o $(dotnet /srv/swapper/Swapper.dll next | grep "Working" | sed 's/^.*: //' | tr -d ' ')
            sudo systemctl restart $(dotnet /srv/swapper/Swapper.dll next | grep "Daemon" | sed 's/^.*: //' | tr -d ' ')
            sleep 5
            sudo dotnet /srv/swapper/Swapper.dll swap
