name: Production pushing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH commmands on remote server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command: | 
            cd "/source/ServerProduction/BeatSlayerServer"
            git pull origin master
            sudo dotnet publish -c release -o $(/srv/swapper/Swapper.dll next | grep "Working" | sed 's/^.*: //' | tr -d ' ')
            sudo systemctl status $(/srv/swapper/Swapper.dll next | grep "Daemon" | sed 's/^.*: //' | tr -d ' ')
            sudo /srv/swapper/Swapper.dll swap
