name: secret

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Execute SSH commmands on remote server
        uses: appleboy/ssh-action@master
        env:
            SSH_KEY: ${{secrets.HOST}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "$SSH_KEY" > key
